[build]
  command = "sed -i \"s|API_KEY|${API_KEY}|g\" netlify.toml && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://api.themoviedb.org/3/:splat&api_key=API_KEY"
  status = 200
  force = true # COMMENT: ensure that we always redirect