[build]
  command = "sed -i \"s|API_KEY|${API_KEY}|g\" netlify.toml && npm run build"

[[redirects]]
  from = "/api/movie/*"
  to = "https://api.themoviedb.org/3/movie/:splat?api_key=API_KEY"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/api/configuration"
  to = "https://api.themoviedb.org/3/configuration?api_key=API_KEY"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/api/discover/movie"
  to = "https://api.themoviedb.org/3/discover/movie?language=us_EN&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&with_original_language=ja&api_key=API_KEY"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200